### ISSUE TITLE
Header case normalization

### ISSUE THREAD

**Issue by diamondburned** [cmyui/cmyui_pkg#3]
According to RFC7230, header field names must be "case-insensitive," and most HTTP implementations seem to normalize the casing. This implementation, however, does not:

https://github.com/cmyui/cmyui_pkg/blob/67ce2c89439aec619432994a686fcc037953d4c5/cmyui/web.py#L254-L262

Most HTTP servers will normalize the HTTP header casing, so `X-Real-IP` would therefore become `X-Real-Ip`. However, in this implementation, [the user might check for `X-Real-IP` instead][cho.py], which would yield nothing when responding to a client compliant with the normalized headers:

```py
resp, token = await login(
    conn.body, conn.headers['X-Real-IP']
)
```

[cho.py]: https://github.com/cmyui/gulag/blob/2ca7f179986c34a64101bd48f5f06c3e584fac91/domains/cho.py#L70

The proper fix to this issue would probably be to add casing normalization to both the header parsing code and the header getting code. Python's `urllib` had a similar patch [here](https://bugs.python.org/issue2275).

**Comment by cmyui** [comment]
Yeah I agree, and that's probably indeed the way to go about it.

I'd imagine there are probably quite a few other differences between my implementation and the standards, a lot of the code used in /web here was from my first attempt at writing all this stuff and I rarely used any references when writing it.

I've already got some ideas for improvements & refactoring, I'm pretty tight on time right now but when I get some more I'll make sure to read through the protocol standards and do more the right way for the next major refactoring. :P

Thanks for the high quality issue!
